Update deployment workflows to include Docker image env var and adjust SSL config

diff --git a/.github/workflows/deploy-dev.yml b/.github/workflows/deploy-dev.yml
--- a/.github/workflows/deploy-dev.yml
+++ b/.github/workflows/deploy-dev.yml
@@ -66,6 +66,7 @@ jobs:
           script: |
             echo "Creating .env.fast-api-youtub-playlist-downloader.dev file on server"
             cat <<EOF > .env.fast-api-youtub-playlist-downloader.dev
+            DOCKER_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/fast-api-youtub-playlist-downloader:dev
             
             # ==========================================
             # ⬇️ ADD YOUR CUSTOM ENVIRONMENT VARIABLES ⬇️
@@ -84,7 +85,7 @@ jobs:
     runs-on: ubuntu-latest
     needs: [update-environment]
     env:
-      SETUP_SSL: true # Set to 'true' to enable SSL setup with Certbot and Nginx
+      SETUP_SSL: false # Set to 'true' to enable SSL setup with Certbot and Nginx
     steps:
       - name: Deploy and restart Docker containers
         uses: appleboy/ssh-action@master
@@ -194,7 +195,7 @@ jobs:
 
             # Setup SSL certificates with Certbot
             echo "Setting up SSL certificates..."
-            sudo certbot --nginx -d api-dev.example.com --non-interactive --agree-tos --email nwaforglory6@gmail.com --redirect || echo "SSL setup failed, continuing with HTTP"
+            sudo certbot --nginx -d api-dev.example.com --non-interactive --agree-tos --email admin@example.com --redirect || echo "SSL setup failed, continuing with HTTP"
 
             # Setup automatic renewal
             sudo systemctl enable certbot.timer
diff --git a/.github/workflows/deploy-prod.yml b/.github/workflows/deploy-prod.yml
--- a/.github/workflows/deploy-prod.yml
+++ b/.github/workflows/deploy-prod.yml
@@ -65,6 +65,7 @@ jobs:
           script: |
             echo "Creating .env.fast-api-youtub-playlist-downloader.prod file on server"
             cat <<EOF > .env.fast-api-youtub-playlist-downloader.prod
+            DOCKER_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/fast-api-youtub-playlist-downloader:prod
             # Core Django
 
             # ==========================================
@@ -209,7 +210,7 @@ jobs:
 
             # Setup SSL certificates with Certbot
             echo "Setting up SSL certificates..."
-            sudo certbot --nginx -d api.example.com --non-interactive --agree-tos --email nwaforglory6@gmail.com --redirect || echo "SSL setup failed, continuing with HTTP"
+            sudo certbot --nginx -d api.example.com --non-interactive --agree-tos --email admin@example.com --redirect || echo "SSL setup failed, continuing with HTTP"
 
             # Setup automatic renewal
             sudo systemctl enable certbot.timer
